[package]
name = "springbok"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "springbok_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
tauri = { version = "2.0.1", features = [] }
tauri-plugin-shell = "2.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
imageoptimize = "0.1.5"
snafu = "0.8.5"
tokio = { version = "1.40.0", default-features = false, features = ["fs"] }
blake3 = "1.5.4"
tauri-plugin-os = "2.0.1"
once_cell = "1.20.1"
glob = "0.3.1"
