[package]
name = "image-converter"
version = "0.1.1"
authors = ["tree.xie@outlook.com"]
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avif-decode = "0.2.2"
bytesize = "1.3.0"
crossbeam-channel = "0.5.8"
dssim = "3.2.4"
glob = "0.3.1"
home = "0.5.5"
image = { version = "0.24.7", features = ["webp-encoder", "avif-encoder"] }
imagequant = { version = "4.2.1", default-features = false }
lodepng = "3.9.0"
mozjpeg = "0.10.3"
once_cell = "1.18.0"
parking_lot = "0.12.1"
rfdx = "0.1.2"
rgb = "0.8.36"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
slint = "1.2.1"
snafu = "0.7.5"
substring = "1.4.5"
time = "0.3.29"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["local-time"] }

[build-dependencies]
slint-build = "1.2.1"

[profile.release]
codegen-units = 1
lto = true
