[package]
name = "image-converter"
version = "0.1.0"
authors = ["tree.xie@outlook.com"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.2.0"

[build-dependencies]
slint-build = "1.2.0"
