[package]
name = "image-converter"
version = "0.1.0"
authors = ["tree.xie@outlook.com"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.3.0"
crossbeam-channel = "0.5.8"
glob = "0.3.1"
once_cell = "1.18.0"
rfd = "0.12.0"
rgb = "0.8.36"
slint = "1.2.0"
snafu = "0.7.5"
image = { version = "0.24.7", features = ["webp-encoder", "avif-encoder"]}
imagequant = { version = "4.2.1", default-features = false }
lodepng = "3.7.2"
avif-decode = "0.2.2"
mozjpeg = "0.10.1"
dssim = "3.2.4"
substring = "1.4.5"

[build-dependencies]
slint-build = "1.2.0"

[profile.release]
codegen-units = 1
lto = true