[package]
name = "springbok"
version = "0.1.4"
authors = ["tree.xie@outlook.com"]
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avif-decode = "0.2.2"
bytesize = "1.3.0"
crossbeam-channel = "0.5.9"
dssim = "3.2.4"
glob = "0.3.1"
home = "0.5.9"
image = { version = "0.24.7", features = ["webp-encoder", "avif-encoder"] }
imagequant = { version = "4.2.2", default-features = false }
lodepng = "3.9.2"
mozjpeg = "0.10.5"
once_cell = "1.19.0"
parking_lot = "0.12.1"
rfdx = "0.1.2"
rgb = "0.8.37"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.28"
slint = "1.3.2"
snafu = "0.7.5"
substring = "1.4.5"
time = "0.3.31"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["local-time"] }

[build-dependencies]
slint-build = "1.3.2"

[profile.release]
codegen-units = 1
lto = true
