[package]
name = "image-converter"
version = "0.1.0"
authors = ["tree.xie@outlook.com"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.3.0"
glob = "0.3.1"
rfd = "0.12.0"
slint = "1.2.0"
snafu = "0.7.5"
tokio = { version = "1.32.0", features = ["macros", "rt", "rt-multi-thread", "time"]}

[build-dependencies]
slint-build = "1.2.0"
