name: "publish"
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
    # branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: release
        run: |
          uname -v
          brew install nasm
          make release
          make macos
          tar -czvf ImageConverter-darwin-x86_64.tar.gz ImageConverter.app
          ./.github/workflows/upload_asset.sh ./ImageConverter-darwin-x86_64.tar.gz $GITHUB_TOKEN
  macos-aarch:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install target
        run: |
          rustup update
          rustup target add aarch64-apple-darwin
      - name: release
        run: |
          uname -v
          cargo build --release --target=aarch64-apple-darwin
          mv ./target/aarch64-apple-darwin/release/springbok ./macos/Contents/MacOS/
          mv ./macos ./ImageConverter.app
          tar -czvf ImageConverter-darwin-aarch64.tar.gz ImageConverter.app
          ./.github/workflows/upload_asset.sh ./ImageConverter-darwin-aarch64.tar.gz $GITHUB_TOKEN
        

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ilammy/setup-nasm@v1
      - name: release
        run: make release
      - name: Upload Assets
        run: |
          mv target/release/springbok.exe ./springbok-windows.exe
          ./.github/workflows/upload_asset.sh ./springbok-windows.exe $GITHUB_TOKEN

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ilammy/setup-nasm@v1
      - name: release
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev
          make release
      - name: Upload Assets
        run: |
          mv target/release/springbok ./springbok-linux
          ./.github/workflows/upload_asset.sh ./springbok-linux $GITHUB_TOKEN