name: "test"
on:
  push:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ilammy/setup-nasm@v1
      - name: release
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev
          make release
  # windows:
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #     - uses: ilammy/setup-nasm@v1
  #     - name: release
  #       run: make release